"功能" = "累计采购合同"
"表名" = "ADS_LJCGHT"
"编号" = 1
"状态" = "完成"

"MySQL原逻辑" = '''
SELECT
    497561 + COUNT(1) jnhtsl,
    1293206745239.63 + SUM(A.JE) jnhtje
FROM
    cght A
WHERE
    A.SWBZ = '2'
    AND A.WJBZ = '0'
    AND LEFT (A.SPRQ, 4) > 2020
---
SELECT
    137124734058.8 + SUM(A.JE) nbxtjnhtje
FROM
    cght A
WHERE
    A.SWBZ = '2'
    AND A.WJBZ = '0'
    AND EXISTS (
        SELECT
            1
        FROM
            xtghdw B
        WHERE
            A.DWBM = B.DWBM
            AND B.FOREBSJBFL = '0'
    )
    AND LEFT (A.SPRQ, 4) > 2020
'''


"ETL脚本" = '''
select
    md5 (uuid ()) as id,
    null as etl_time,
    497561 + count(1) as ljcght,
    1293206745239.63 + sum(je) as ljcghtje,
    137124734058.8 + sum(if (forebsjbfl = '0', je, 0)) as nbxtje
from
    dw_dsep.DWS_CGHT
where
    year (sprq) > 2020
'''

"ADS查询" = '''
select
    ljcght, -- 累计采购合同
    ljcghtje, -- 累计采购合同金额
    nbxtje -- 内部协同金额
from
    ADS_LJCGHT
'''

