"功能" = "累计采购合同二级页面"
"表名" = "ADS_LJCGHT_SECOND"
"编号" = 2
"状态" = "完成"

"MySQL原逻辑" = '''
SELECT
    (@i:=@i+1) AS sequence,
    LEFT(A.SPRQ,4) years,
    ROUND(COUNT(1)/ 10000, 2) contractTotal,
    ROUND(SUM(A.JE)/ 100000000, 2) contractMoney
FROM
    cght A,(Select @i:=${(pageNum-1)*pageSize}) B
WHERE
    A.SWBZ = '2'
    AND A.WJBZ = '0'
    AND LEFT(A.SPRQ,4) > 2020
GROUP BY
    LEFT(A.SPRQ,4)
ORDER BY
    LEFT(A.SPRQ,4)
    DESC
LIMIT ${(pageNum-1)*pageSize},${pageSize}
'''

"ETL脚本" = '''
select
    md5 (concat ('-', strleft (sprq, 4))) as id,
    null as etl_time,
    strleft (sprq, 4) as years,
    round(count(1) / 10000, 2) as ljcghtfs,
    round(sum(je) / 100000000, 2) as ljhtje
from
    dw_dsep.DWS_CGHT
where
    year (sprq) > 2020
group by
    years
'''

"ADS查询" = '''
select
    years, -- 年度
    ljcghtfs, -- 累计采购合同份数：万份
    ljhtje -- 累计采购合同金额：亿元
from
    ADS_LJCGHT_SECOND
order by
    years desc
'''


