"功能" = "累计采购合同四级页面"
"表名" = "ADS_LJCGHT_FOUR"
"编号" = 4
"状态" = "取消"


"MySQL原逻辑" = '''
-- 采购页面总览 点击直管单位 四级页面
-- interiorFourLevel
SELECT
    (@i:=@i+1) AS sequence,
    (SELECT DWMC FROM xtlldw WHERE DWBM = LEFT(A.XFDM, 6)) companyName,
    ROUND(COUNT(1)/10000, 2) contractTotal,
    ROUND(SUM(A.JE)/100000000, 2) contractMoney
FROM cght A,(Select @i:=${(pageNum-1)*pageSize}) B
WHERE A.SWBZ = '2'
    AND A.WJBZ = '0'
    AND LEFT(A.SPRQ, 4) = #{year}
    AND LEFT(A.XFDM, 3) = ( SELECT DWBM FROM XTLLDW WHERE DWMC = #{xfdm})
GROUP BY LEFT(A.XFDM, 6)
    LIMIT ${(pageNum-1)*pageSize},${pageSize}
'''

"ETL脚本" = '''
select
    md5 (concat_ws ('-', cgdwmc, strleft (sprq, 4))) as id,
    null as etl_time,
    zgdwmc,
    cgdwmc,
    strleft (sprq, 4) as years,
    round(count(1) / 10000, 2) as sl,
    round(sum(je) / 100000000, 2) as je
from
    dw_dsep.DWS_CGHT
where
    year (sprq) > 2020
group by
    zgdwmc,
    cgdwmc,
    years
'''



"ADS查询" = '''
select
    cgdwmc, -- 采购单位名称（三级单位名称）
    sl, -- 累计合同份数(万份)
    je -- 累计合同额(亿元)
from
    ADS_LJCGHT_FOUR
where
    years = '2023'
    and zgdwmc = '五矿地产有限公司'
'''

