"功能" = "内部协同金额二级页面"
"表名" = "ADS_NBXTJE_SECOND"
"编号" = 5
"状态" = "完成"

"MySQL原逻辑" = '''
-- 内部协同采购金额、点击后 二级页面
-- purchaseAmountSecondLevel
SELECT
    (@i:=@i+1) AS sequence,
    LEFT(A.SPRQ, 4) AS years,
    A.BUSINESSCLASSIFICATION AS lx,
    0 AS materials,
    0 AS project,
    0 AS serve,
    ROUND(SUM(A.JE)/100000000, 2) AS money,
    0 as totalMoney
FROM cght A,(Select @i:=0) B
WHERE A.SWBZ = '2'
    AND A.WJBZ = '0'
    AND LEFT(A.SPRQ,4) > 2020
    AND EXISTS (SELECT 1 FROM xtghdw B WHERE A.DWBM = B.DWBM AND B.FOREBSJBFL = '0')
GROUP BY LEFT(A.SPRQ, 4) ,A.BUSINESSCLASSIFICATION
ORDER BY LEFT(A.SPRQ, 4) DESC ,A.BUSINESSCLASSIFICATION DESC
'''


"ETL脚本" = '''
select
    md5 (
        concat_ws ('-', strleft (sprq, 4), businessclassification)
    ) as id,
    null as etl_time,
    businessclassification as lx,
    strleft (sprq, 4) as years,
    round(sum(je) / 100000000, 2) as je
from
    dw_dsep.DWS_CGHT
where
    year (sprq) > 2020
    and forebsjbfl = '0'
group by
    years,
    businessclassification
'''


"ADS查询" = '''
select
    years, -- 年度
    lx, -- 协同类型
    je -- 累计金额：亿元
from
    ADS_NBXTJE_SECOND
order by
    years desc,
    lx desc
'''
