"功能" = "内部协同金额四级页面"
"表名" = "ADS_NBXTJE_FOUR"
"编号" = 7
"状态" = "取消"

"MySQL原逻辑" = '''
-- 内部协同采购金额 点击直管单位 四级页面
-- purchaseAmountFourLevel
select
    @i := @i + 1 as sequence,
    (
        select
            DWMC
        from
            xtlldw
        where
            DWBM = LEFT (A.XFDM, 6)
    ) as companyName,
    A.BUSINESSCLASSIFICATION as lx,
    0 as materials,
    0 as project,
    0 as serve,
    ROUND(sum(A.JE) / 100000000, 2) as money,
    0 as totalMoney
from
    cght A,
    (
        select 0
    ) B
where
    A.SWBZ = '2'
    and A.WJBZ = '0'
    and exists (
        select
            1
        from
            xtghdw B
        where
            A.DWBM = B.DWBM
            and B.FOREBSJBFL = '0'
    )
    and LEFT (A.SPRQ, 4) = #{year}
    and left (A.XFDM, 3) = (
        SELECT
            DWBM
        FROM
            XTLLDW
        WHERE
            DWMC = #{xfdm}
    ) 
group by
    LEFT (A.XFDM, 6),
    A.BUSINESSCLASSIFICATION
order by
    LEFT (A.XFDM, 6),
    A.BUSINESSCLASSIFICATION desc
'''

"ETL脚本" = '''
select
    md5 (
        concat_ws (
            '-',
            strleft (sprq, 4),
            businessclassification,
            cgdwmc
        )
    ) as id,
    null as etl_time,
    zgdwmc,
    cgdwmc,
    businessclassification as lx,
    strleft (sprq, 4) as years,
    round(sum(je) / 100000000, 2) as money
from
    dw_dsep.DWS_CGHT
where
    year (sprq) > 2020
    and forebsjbfl = '0'
group by
    years,
    zgdwmc,
    cgdwmc,
    lx
'''

"ADS查询" = '''
select
    cgdwmc, -- 采购单位名称（三级单位名称）
    lx, -- 协同类型
    money -- 累计合同额(亿元)
from
    ADS_NBXTJE_FOUR
where
    years = '2023'
    and zgdwmc = '五矿地产有限公司'
order by
    cgdwmc,
    lx
'''
