"功能" = "近4年合同数量"
"表名" = "ADS_JSNHTSL"
"编号" = 17
"状态" = "完成"

"MySQL原逻辑" = '''
SELECT
    LEFT (A.SPRQ, 4) nf,
    COUNT(1) sl
FROM
    CGHT A
WHERE
    A.SWBZ = '2'
    AND A.WJBZ = '0'
    AND (A.HTBM like #{year} OR A.HTBM like #{year1} OR A.HTBM like #{year2} OR A.HTBM like #{year3})
    AND LEFT (A.SPRQ, 4) is NOT NULL
GROUP BY
    LEFT (A.SPRQ, 4)
ORDER BY
    LEFT (A.SPRQ, 4)
'''



"ETL脚本" = '''
select
    md5 (strleft (htbm, 4)) as id,
    null as etl_time,
    strleft (htbm, 4) as years,
    count(1) as sl
from
    dw_dsep.DWD_GYL_CGHT
where
    swbz = '2'
    and wjbz = '0'
    and cast(strleft (htbm, 4) as int) > year (curdate ()) - 4
group by
    years
'''



"ADS查询" = '''
select
    years, -- 年份
    sl -- 金额
from
    ADS_JSNHTSL
order by
    years
'''
