"功能" = "风险处理监控三级页面"
"表名" = "ADS_FXYJ_THREE"
"编号" = 2
"状态" = "完成"

"MySQL原逻辑" = '''
SELECT
    A.ID,
    B.ZGRMC,
    B.YQWCSJ,
    B.JSSJSJ,
    CASE B.ZT
        WHEN 0 THEN '整改通知未发布'
        WHEN 1 THEN '整改报告未提交'
        WHEN 2 THEN '整改报告已提交'
        WHEN 3 THEN '整改报告不合格'
        WHEN 9 THEN '整改完成'
    END ZGZT
FROM
    ztb_jk_yjxx A,
    ZTB_JK_ZGTZ B
    LEFT JOIN ZTB_JK_DBXX C ON B.ID = C.ZGTZID
WHERE
    A.ID = B.YJXXID
'''

"ETL脚本" = '''
select
    uid,
    id,
    zgrmc,
    yqwcsj,
    jssjsj,
    zgzt,
    etl_time
from
    (
        with
            main as (
                select
                    a.id,
                    b.zgrmc,
                    b.yqwcsj,
                    b.jssjsj,
                    case b.zt
                        when 0 then '整改通知未发布'
                        when 1 then '整改报告未提交'
                        when 2 then '整改报告已提交'
                        when 3 then '整改报告不合格'
                        when 9 then '整改完成'
                    end as zgzt
                from
                    dw_dsep.DWD_GYL_ZTB_JK_YJXX as a
                    inner join dw_dsep.DWD_GYL_ZTB_JK_ZGTZ as b on a.id = b.yjxxid
                    left join dw_dsep.DWD_GYL_ZTB_JK_DBXX as c on b.id = c.zgtzid
            ),
            ads as (
                select
                    md5 (concat_ws ('-', id, zgrmc, yqwcsj, jssjsj, zgzt)) as uid,
                    cast(null as datetime) as etl_time,
                    main.*
                from
                    main
            )
        select
            *
        from
            ads
    ) as ads
'''

