"功能" = "今日风险预警二级页面已处理"
"表名" = "ADS_JRFXYJ_SECOND_YCL"
"编号" = 4
"状态" = "完成"

"MySQL原逻辑" = '''
SELECT
    id
FROM
    ZTB_JK_YJXX A
WHERE
    A.ZT = '2'
'''

"ETL脚本" = '''
select
    md5 (id) as uid,
    cast(null as datetime) as etl_time,
    id
from
    dw_dsep.DWD_GYL_ZTB_JK_YJXX
where
    zt = '2'
'''

