"功能" = "今日风险预警二级页面异常数据"
"表名" = "ADS_JRFXYJ_SECOND_YC"
"编号" = 5
"状态" = "完成"

"MySQL原逻辑" = '''
SELECT
    id
FROM
    ZTB_JK_YJXX A
WHERE
    A.YCZT = '1'
'''

"ETL脚本" = '''
select
    md5(id) as uid,
    null as etl_time,
    id
from
    dw_dsep.DWD_GYL_ZTB_JK_YJXX
where
    yczt = '1'
'''

