"功能" = "风险闭环处置监控二级页面处置完成"
"表名" = "ADS_FXBHCZJK_SECOND_CZWC"
"编号" = 9
"状态" = "完成"

"MySQL原逻辑" = '''
select
    id
from
    (
        SELECT
            id
        FROM
            ZTB_JK_YJXX A
        WHERE
            A.ZT = '2'
            and TYPE not in ('GYS')
        group by
            YJLXID,
            ZBBM
        union all
        SELECT
            id
        FROM
            ZTB_JK_YJXX A
        WHERE
            A.ZT = '2'
            and TYPE in ('GYS')
    ) b
limit
    500
'''

"ETL脚本" = '''
select
    uid,
    id,
    etl_time
from
    (
        with
            main as (
                select
                    any_value (id) as id
                from
                    dw_dsep.DWD_GYL_ZTB_JK_YJXX
                where
                    ZT = '2'
                    and `TYPE` != 'GYS'
                group by
                    yjlxid,
                    zbbm
                union all
                select
                    id
                from
                    dw_dsep.DWD_GYL_ZTB_JK_YJXX
                where
                    ZT = '2'
                    and `type` = 'GYS'
            ),
            ads as (
                select
                    md5 (id) as uid,
                    null as etl_time,
                    id
                from
                    main
            )
        select
            *
        from
            ads
    ) as ads
limit 500
'''

