"功能" = "超时未处置分析二级页面"
"表名" = "ADS_CSWCZFX_SECOND"
"编号" = 11
"状态" = "完成"

"MySQL原逻辑" = '''
SELECT
    A.*,
    left (b.djdwbm, 3) zgdwCode, -- 直管单位
    b.djdwbm zbdwCode -- 招标单位编码
FROM
    (
        -- 派单超时
        (
            SELECT
                A.ID,
                A.YJLXID,
                A.ZBZDRMC,
                A.TYPE, -- 场景
                A.ZBZDRDWMC, -- 采购单位
                A.YJFS, -- 预警方式
                A.YJJB, -- 预警级别
                A.ZT, -- 处置状态
                '派单超时未处理' AS cause, -- 异常原因
                A.ZBBM, -- 招标编码
                A.YJSJ, -- 发现时间
                A.YJNR, -- 风险内容
                C.SHRMC, -- 督办人
                C.BDBRMC, -- 处置人
                C.SHRDWMC, -- 督办单位
                B.YQWCSJ, -- 要求完成时间
                C.DBRQ, -- 督办时间
                CASE B.ZT
                    WHEN 0 THEN '整改通知未发布'
                    WHEN 1 THEN '整改报告未提交'
                    WHEN 2 THEN '整改报告已提交'
                    WHEN 3 THEN '整改报告不合格'
                    WHEN 9 THEN '整改完成'
                END ZGZT, -- 处置状态
                CASE A.DBZT
                    WHEN 0 THEN '未督办'
                    WHEN 1 THEN '已督办'
                    WHEN 2 THEN '已反馈'
                    WHEN 3 THEN '已接收'
                    ELSE '未督办'
                END DBZT -- 督办进度
            FROM
                ZTB_JK_YJXX A,
                ZTB_JK_ZGTZ B
                LEFT JOIN ZTB_JK_DBXX C ON B.ID = C.ZGTZID
            WHERE
                A.ID = B.YJXXID
                AND A.YJFS = '0'
                AND A.YCZT = '1'
        )
        union all
        -- 已移交上级单位督办
        (
            SELECT
                A.ID,
                A.YJLXID,
                A.ZBZDRMC,
                A.TYPE,
                A.ZBZDRDWMC,
                A.YJFS,
                A.YJJB,
                A.ZT,
                '已移交上级单位督办' AS cause,
                A.ZBBM,
                A.YJSJ,
                A.YJNR,
                C.SHRMC, -- 督办人
                C.BDBRMC, -- 处置人
                C.SHRDWMC, -- 督办单位
                B.YQWCSJ, -- 要求完成时间
                C.DBRQ, -- 督办时间
                CASE B.ZT
                    WHEN 0 THEN '整改通知未发布'
                    WHEN 1 THEN '整改报告未提交'
                    WHEN 2 THEN '整改报告已提交'
                    WHEN 3 THEN '整改报告不合格'
                    WHEN 9 THEN '整改完成'
                END ZGZT, -- 处置状态
                CASE A.DBZT
                    WHEN 0 THEN '未督办'
                    WHEN 1 THEN '已督办'
                    WHEN 2 THEN '已反馈'
                    WHEN 3 THEN '已接收'
                    ELSE '未督办'
                END DBZT -- 督办进度
            FROM
                ZTB_JK_YJXX A,
                ZTB_JK_ZGTZ B
                LEFT JOIN ZTB_JK_DBXX C ON B.ID = C.ZGTZID
            WHERE
                A.ID = B.YJXXID
                AND A.YJFS = '0'
                AND A.YCZT = '1'
        )
        union all
        -- 禁止操作
        (
            SELECT
                A.ID,
                A.YJLXID,
                A.ZBZDRMC,
                A.TYPE,
                A.ZBZDRDWMC,
                A.YJFS,
                A.YJJB,
                A.ZT,
                '禁止操作超时未处理' AS cause,
                A.ZBBM,
                A.YJSJ,
                A.YJNR,
                '' SHRMC,
                '' BDBRMC,
                '' SHRDWMC,
                '' YQWCSJ,
                '' DBRQ,
                '' ZGZT,
                '' DBZT
            FROM
                ZTB_JK_YJXX A
            WHERE
                A.ZT = '1'
                AND A.YJFS = '1'
                AND A.YCZT = '1'
        )
    ) A
    LEFT JOIN ZTB_INVITESCHEME B on A.ZBBM = B.INVITENO
'''
"ETL脚本" = '''
select
    uid,
    id,
    yjlxid,
    zbzdrmc,
    type,
    zbzdrdwmc,
    yjfs,
    yjjb,
    zt,
    cause,
    zbbm,
    yjsj,
    yjnr,
    shrmc,
    bdbrmc,
    shrdwmc,
    yqwcsj,
    dbrq,
    zgzt,
    dbzt,
    zgdwcode,
    zbdwcode
from
    (
        with
            dws as (
                select
                    a.id,
                    a.yjlxid,
                    a.zbzdrmc,
                    a.type, -- 场景
                    a.zbzdrdwmc, -- 采购单位
                    a.yjfs, -- 预警方式
                    a.yjjb, -- 预警级别
                    a.zt, -- 处置状态
                    a.zbbm, -- 招标编码
                    a.yjsj, -- 发现时间
                    a.yjnr, -- 风险内容
                    c.shrmc, -- 督办人
                    c.bdbrmc, -- 处置人
                    c.shrdwmc, -- 督办单位
                    b.yqwcsj, -- 要求完成时间
                    c.dbrq, -- 督办时间
                    case b.zt
                        when 0 then '整改通知未发布'
                        when 1 then '整改报告未提交'
                        when 2 then '整改报告已提交'
                        when 3 then '整改报告不合格'
                        when 9 then '整改完成'
                    end zgzt, -- 处置状态
                    case a.dbzt
                        when 0 then '未督办'
                        when 1 then '已督办'
                        when 2 then '已反馈'
                        when 3 then '已接收'
                        else '未督办'
                    end dbzt -- 督办进度
                from
                    dw_dsep.DWD_GYL_ZTB_JK_YJXX as a
                    inner join dw_dsep.DWD_GYL_ZTB_JK_ZGTZ as b on a.id = b.yjxxid
                    left join dw_dsep.DWD_GYL_ZTB_JK_DBXX c on b.id = c.zgtzid
                where
                    a.yjfs = '0'
                    and a.yczt = '1'
            ),
            main as (
                select
                    '派单超时未处理' as cause, -- 异常原因
                    *
                from
                    dws
                union all
                select
                    '已移交上级单位督办' as cause,
                    *
                from
                    dws
                union all
                -- 禁止操作
                select
                    '禁止操作超时未处理' as cause,
                    id,
                    yjlxid,
                    zbzdrmc,
                    type,
                    zbzdrdwmc,
                    yjfs,
                    yjjb,
                    zt,
                    zbbm,
                    yjsj,
                    yjnr,
                    '' as shrmc,
                    '' as bdbrmc,
                    '' as shrdwmc,
                    '' as yqwcsj,
                    '' as dbrq,
                    '' as zgzt,
                    '' as dbzt
                from
                    dw_dsep.DWD_GYL_ZTB_JK_YJXX
                where
                    zt = '1'
                    and yjfs = '1'
                    and yczt = '1'
            ),
            ads as (
                select
                    main.id as uid,
                    strleft (b.djdwbm, 3) as zgdwcode, -- 直管单位
                    b.djdwbm as zbdwcode, -- 招标单位编码
                    main.*
                from
                    main
                    left join dw_dsep.DWD_GYL_ZTB_INVITESCHEME as b on main.zbbm = b.inviteno
            )
        select
            *
        from
            ads
    ) as ads
'''