["基本信息"]
"类型" = "合规管理"
"要素" = "操作时间不合规（依法必招）"
"体征" = "未按时开标"
"应用名称" = "CGHG_25"
"状态" = "开始"


["参数"]
"开始日期" = 2023-01-01
"结束日期" = 2024-09-01


[SQL]
"MySQL测试" = '''
SELECT
    C.INVITENO zbbm,
    C.SCHEMEDESC zbmc,
    C.INVITECORPCODE cgdwbm,
    C.INVITECORPDESC cgdwmc,
    I.BUSI_ENDTIME tbjzsj,
    '开标时间+24小时，仍处于未开标状态' AS yy
FROM
    ZTB_INVITESCHEME C,
    ZTB_INVITE I
WHERE
    C.INVITESCHEMEID = I.INVITESCHEMEID
    AND I.AUDITFLAG = '2'
    AND C.zbxmlx = '1'
    AND I.BUSIBIDOPEN = '0'
    AND I.ABORTINVITE = '0'
    AND DATE_ADD (I.BUSI_BIDOPENTIME, INTERVAL 1 DAY) >= '2024-01-01' --  #{startTime}
    AND DATE_ADD (I.BUSI_BIDOPENTIME, INTERVAL 1 DAY) < '2024-09-01' -- #{endTime}
'''
