["基本信息"]
"类型" = "合规管理"
"要素" = "操作时间不合规（依法必招）"
"体征" = "中标通知书延时"
"应用名称" = "CGHG_29"
"状态" = "ODS测试通过"


["参数"]
"开始日期" = 2024-01-01
"结束日期" = 2024-09-01


[SQL]
"MySQL测试" = '''
SELECT
    C.INVITENO zbbm,
    C.SCHEMEDESC zbmc,
    C.INVITECORPCODE cgdwbm,
    C.INVITECORPDESC cgdwmc,
    P.AUDITTIME zbjggsfbsj,
    '中标结果公示后，未及时发布中标通知书' AS yy
FROM
    ZTB_INVITESCHEME C,
    ZTB_INVITE I,
    ZTB_INTEGRATEAUDIT A,
    ZTB_RESULT_PUBLICITY P
WHERE
    C.INVITESCHEMEID = I.INVITESCHEMEID
    AND I.INVITEID = A.INVITEID
    AND P.AUDITNO = A.AUDITNO
    AND P.AUDITFLAG = '2'
    AND C.zbxmlx = '1'
    AND DATE_ADD (P.AUDITTIME, INTERVAL 10 DAY) >= '2024-01-01' -- #{startTime}
    AND DATE_ADD (P.AUDITTIME, INTERVAL 10 DAY) < '2024-09-01' -- #{endTime}
    AND NOT EXISTS (
        SELECT
            1
        FROM
            ZBTZS Z
        WHERE
            Z.LXBM = C.INVITENO
            AND Z.WORKFLOWSTATUS = '2'
    )
'''


"ETL脚本" = '''
select
    uuid,
    onuse,
    etl_time,
    zgqybm, -- 直管企业编码
    zbbm,
    zbmc,
    cgdwbm,
    cgdwmc,
    zbjggsfbsj,
    yy,
    compare_time
from
    (
        with
            main as (
                select
                    c.inviteno as zbbm,
                    c.schemedesc as zbmc,
                    c.invitecorpcode as cgdwbm,
                    c.invitecorpdesc as cgdwmc,
                    p.audittime as zbjggsfbsj,
                    '中标结果公示后，未及时发布中标通知书' as yy,
                    date_add (p.audittime, interval 10 day) as compare_time
                from
                    dw_ods_dsep.ods_cg_ztb_invitescheme as c
                    inner join dw_ods_dsep.ods_cg_ztb_invite as i on c.inviteschemeid = i.inviteschemeid
                    inner join dw_ods_dsep.ods_cg_ztb_integrateaudit as a on i.inviteid = a.inviteid
                    inner join dw_ods_dsep.ods_cg_ztb_result_publicity as p on p.auditno = a.auditno
                where
                    p.auditflag = '2'
                    and c.zbxmlx = '1'
                    and c.inviteno not in (
                        select
                            lxbm
                        from
                            dw_ods_dsep.ods_cg_zbtzs
                        where
                            workflowstatus = '2'
                    )
            ),
            ads as (
                select
                    md5 (
                        concat_ws (
                            '-',
                            zbbm,
                            zbmc,
                            cgdwbm,
                            cgdwmc,
                            zbjggsfbsj,
                            yy,
                            compare_time
                        )
                    ) as uuid,
                    '0' as onuse,
                    cast(null as datetime) as etl_time,
                    strleft (cgdwbm, 3) as zgqybm, -- 直管企业编码
                    main.*
                from
                    main
            ),
            test as (
                select
                    zbbm,
                    zbmc,
                    cgdwbm,
                    cgdwmc,
                    zbjggsfbsj,
                    yy
                from
                    ads
                where
                    true
                    and compare_time >= '2024-01-01' --  #{startTime}
                    and compare_time < '2024-09-01' -- #{endTime}
            )
        select
            *
        from
            ads
    ) as ads
'''


