["基本信息"]
"类型" = "合规管理"
"要素" = "操作时间不合规（依法必招）"
"体征" = "未按时开标"
"应用名称" = "CGHG_25"
"状态" = "ODS测试通过"


["参数"]
"开始日期" = 2024-01-01
"结束日期" = 2024-09-01


[SQL]
"MySQL测试" = '''
SELECT
    C.INVITENO zbbm,
    C.SCHEMEDESC zbmc,
    C.INVITECORPCODE cgdwbm,
    C.INVITECORPDESC cgdwmc,
    I.BUSI_ENDTIME tbjzsj,
    '开标时间+24小时，仍处于未开标状态' AS yy
FROM
    ZTB_INVITESCHEME C,
    ZTB_INVITE I
WHERE
    C.INVITESCHEMEID = I.INVITESCHEMEID
    AND I.AUDITFLAG = '2'
    AND C.zbxmlx = '1'
    AND I.BUSIBIDOPEN = '0'
    AND I.ABORTINVITE = '0'
    AND DATE_ADD (I.BUSI_BIDOPENTIME, INTERVAL 1 DAY) >= '2024-01-01' --  #{startTime}
    AND DATE_ADD (I.BUSI_BIDOPENTIME, INTERVAL 1 DAY) < '2024-09-01' -- #{endTime}
'''

"ETL脚本" = '''
select
    uuid,
    etl_time,
    zgqybm,
    zbbm,
    zbmc,
    cgdwbm,
    cgdwmc,
    tbjzsj,
    yy,
    compare_time
from
    (
        with
            main as (
                select
                    c.inviteno as zbbm,
                    c.schemedesc as zbmc,
                    c.invitecorpcode as cgdwbm,
                    c.invitecorpdesc as cgdwmc,
                    i.busi_endtime as tbjzsj,
                    '开标时间+24小时，仍处于未开标状态' as yy,
                    date_add (i.busi_bidopentime, interval 1 day) as compare_time
                from
                    dw_ods_dsep.ods_cg_ztb_invitescheme as c
                    inner join dw_ods_dsep.ods_cg_ztb_invite as i on 
                        c.inviteschemeid = i.inviteschemeid
                where
                    i.auditflag = '2'
                    and c.zbxmlx = '1'
                    and i.busibidopen = '0'
                    and i.abortinvite = '0'
            ),
            ads as (
                select
                    md5 (
                        concat_ws (
                            '-',
                            zbbm,
                            zbmc,
                            cgdwbm,
                            cgdwmc,
                            tbjzsj,
                            yy,
                            compare_time
                        )
                    ) as uuid,
                    '0' as onuse,
                    cast(null as datetime) as etl_time,
                    strleft (cgdwbm, 3) as zgqybm, -- 直管企业编码
                    main.*
                from
                    main
            ),
            test as (
                select
                    zbbm,
                    zbmc,
                    cgdwbm,
                    cgdwmc,
                    tbjzsj,
                    yy
                from
                    ads
                where
                    true
                    and compare_time >= '2024-01-01' --  #{startTime}
                    and compare_time < '2024-09-01' -- #{endTime}
            )
        select
            *
        from
            ads
    ) as ads
'''