[["古诗"]]
"标题" = "苔"
"朝代" = "清"
"作者" = "袁枚"
"内容" = "白日不到处，青春恰自来。苔花如米小，也学牡丹开。"

[["古诗"]]
"标题" = "小儿垂钓"
"朝代" = "唐"
"作者" = "胡令能"
"内容" = "蓬头稚子学垂纶，侧坐莓苔草映身。路人借问遥招手，怕得鱼惊不应人。"

[["古诗"]]
"标题" = "苏溪亭"
"朝代" = "唐"
"作者" = "戴叔伦"
"内容" = "苏溪亭上草漫漫，谁倚东风十二阑。燕子不归春事晚，一汀烟雨杏花寒。"

[["古诗"]]
"标题" = "春晓"
"朝代" = "唐"
"作者" = "孟浩然"
"内容" = "春眠不觉晓，处处闻啼鸟。夜来风雨声，花落知多少。"

[["古诗"]]
"标题" = "咏鹅"
"朝代" = "唐"
"作者" = "骆宾王"
"内容" = "鹅鹅鹅，曲项向天歌。白毛浮绿水，红掌拨清波。"

[["古诗"]]
"标题" = "江雪"
"朝代" = "唐"
"作者" = "柳宗元"
"内容" = "千山鸟飞绝，万径人踪灭。孤舟蓑笠翁，独钓寒江雪。"

[["古诗"]]
"标题" = "静夜思"
"朝代" = "唐"
"作者" = "李白"
"内容" = "床前明月光，疑是地上霜。举头望明月，低头思故乡。"

[["古诗"]]
"标题" = "春夜喜雨"
"朝代" = "唐"
"作者" = "杜甫"
"内容" = "好雨知时节，当春乃发生。随风潜入夜，润物细无声。野径云俱黑，江船火独明。晓看红湿处，花重锦官城。"

[["古诗"]]
"标题" = "早春呈水部张十八员外"
"朝代" = "唐"
"作者" = "韩愈"
"内容" = "天街小雨润如酥，草色遥看近却无。最是一年春好处，绝胜烟柳满皇都。"

[["古诗"]]
"标题" = "寻隐者不遇"
"朝代" = "唐"
"作者" = "贾岛"
"内容" = "松下问童子，言师采药去。只在此山中，云深不知处。"

[["古诗"]]
"标题" = "渔歌子"
"朝代" = "唐"
"作者" = "张志和"
"内容" = "西塞山前白鹭飞，桃花流水鳜鱼肥。青箬笠，绿蓑衣，斜风细雨不须归。"

[["古诗"]]
"标题" = "登鹳雀楼"
"朝代" = "唐"
"作者" = "王之涣"
"内容" = "白日依山尽，黄河入海流。欲穷千里目，更上一层楼。"

[["古诗"]]
"标题" = "小池"
"朝代" = "宋"
"作者" = "杨万里"
"内容" = "泉眼无声惜细流，树阴照水爱晴柔。小荷才露尖尖角，早有蜻蜓立上头。"

[["古诗"]]
"标题" = "清明"
"朝代" = "唐"
"作者" = "杜牧"
"内容" = "清明时节雨纷纷，路上行人欲断魂。借问酒家何处有，牧童遥指杏花村。"

[["古诗"]]
"标题" = "咏柳"
"朝代" = "唐"
"作者" = "贺知章"
"内容" = "碧玉妆成一树高，万条垂下绿丝绦。不知细叶谁裁出，二月春风似剪刀。"

[["古诗"]]
"标题" = "悯农"
"朝代" = "唐"
"作者" = "李绅"
"内容" = "锄禾日当午，汗滴禾下土。谁知盘中餐，粒粒皆辛苦。"

[["古诗"]]
"标题" = "饮湖上初晴后雨"
"朝代" = "宋"
"作者" = "苏轼"
"内容" = "水光潋滟晴方好，山色空蒙雨亦奇。欲把西湖比西子，淡妆浓抹总相宜。"

[["古诗"]]
"标题" = "登乐游原"
"朝代" = "唐"
"作者" = "李商隐"
"内容" = "向晚意不适，驱车登古原。夕阳无限好，只是近黄昏。"

[["古诗"]]
"标题" = "赋得古原草送别"
"朝代" = "唐"
"作者" = "白居易"
"内容" = "离离原上草，一岁一枯荣。野火烧不尽，春风吹又生。远芳侵古道，晴翠接荒城。又送王孙去，萋萋满别情。"

[["古诗"]]
"标题" = "千字文"
"朝代" = "南北朝"
"作者" = "周兴嗣"
"内容" = "天地玄黄，宇宙洪荒。日月盈昃，辰宿列张。寒来暑往，秋收冬藏。闰余成岁，律吕调阳……"

[["古诗"]]
"标题" = "画"
"朝代" = "唐"
"作者" = "王维"
"内容" = "远看山有色，近听水无声。春去花还在，人来鸟不惊。"

[["古诗"]]
"标题" = "送孟浩然之广陵"
"朝代" = "唐"
"作者" = "李白"
"内容" = "故人西辞黄鹤楼，烟花三月下扬州。孤帆远影碧空尽，唯见长江天际流。"

[["古诗"]]
"标题" = "晓出净慈寺送林子方"
"朝代" = "宋"
"作者" = "杨万里"
"内容" = "毕竟西湖六月中，风光不与四时同。接天莲叶无穷碧，映日荷花别样红。"

[["古诗"]]
"标题" = "白云泉"
"朝代" = "唐"
"作者" = "白居易"
"内容" = "天平山上白云泉，云自无心水自闲。何必奔冲山下去，更添波浪向人间。"

[["古诗"]]
"标题" = "九月九日忆山东兄弟"
"朝代" = "唐"
"作者" = "王维"
"内容" = "独在异乡为异客，每逢佳节倍思亲。遥知兄弟登高处，遍插茱萸少一人。"

[["古诗"]]
"标题" = "早发白帝城"
"朝代" = "唐"
"作者" = "李白"
"内容" = "朝辞白帝彩云间，千里江陵一日还。两岸猿声啼不住，轻舟已过万重山。"

[["古诗"]]
"标题" = "赠汪伦"
"朝代" = "唐"
"作者" = "李白"
"内容" = "李白乘舟将欲行，忽闻岸上踏歌声。桃花潭水深千尺，不及汪伦送我情。"

[["古诗"]]
"标题" = "望天门山"
"朝代" = "唐"
"作者" = "李白"
"内容" = "天门中断楚江开，碧水东流至此回。两岸青山相对出，孤帆一片日边来。"

[["古诗"]]
"标题" = "梅花"
"朝代" = "宋"
"作者" = "王安石"
"内容" = "墙角数枝梅，凌寒独自开。遥知不是雪，为有暗香来。"

[["古诗"]]
"标题" = "夜宿山寺"
"朝代" = "唐"
"作者" = "李白"
"内容" = "危楼高百尺，手可摘星辰。不敢高声语，恐惊天上人。"

[["古诗"]]
"标题" = "题都城南庄"
"朝代" = "唐"
"作者" = "崔护"
"内容" = "去年今日此门中，人面桃花相映红。人面不知何处去，桃花依旧笑春风。"

[["古诗"]]
"标题" = "宿建德江"
"朝代" = "唐"
"作者" = "孟浩然"
"内容" = "移舟泊烟渚，日暮客愁新。野旷天低树，江清月近人。"

[["古诗"]]
"标题" = "鸟鸣涧"
"朝代" = "唐"
"作者" = "王维"
"内容" = "人闲桂花落，夜静春山空。月出惊山鸟，时鸣春涧中。"

[["古诗"]]
"标题" = "望庐山瀑布"
"朝代" = "唐"
"作者" = "李白"
"内容" = "日照香炉生紫烟，遥看瀑布挂前川。飞流直下三千尺，疑是银河落九天。"

[["古诗"]]
"标题" = "相思"
"朝代" = "唐"
"作者" = "王维"
"内容" = "红豆生南国，春来发几枝。愿君多采撷，此物最相思。"

[["古诗"]]
"标题" = "绝句（两个黄鹂）"
"朝代" = "唐"
"作者" = "杜甫"
"内容" = "两个黄鹂鸣翠柳，一行白鹭上青天。窗含西岭千秋雪，门泊东吴万里船。"

[["古诗"]]
"标题" = "池上"
"朝代" = "唐"
"作者" = "白居易"
"内容" = "小娃撑小艇，偷采白莲回。不解藏踪迹，浮萍一道开。"

[["古诗"]]
"标题" = "金陵晚望"
"朝代" = "唐"
"作者" = "高蟾"
"内容" = "曾伴浮云归晚翠，犹陪落日泛秋声。世间无限丹青手，一片伤心画不成。"

[["古诗"]]
"标题" = "长歌行"
"朝代" = "汉"
"作者" = "乐府"
"内容" = "青青园中葵，朝露待日晞。阳春布德泽，万物生光辉。常恐秋节至，焜黄华叶衰。百川东到海，何时复西归？少壮不努力，老大徒伤悲。"

[["古诗"]]
"标题" = "山村咏怀"
"朝代" = "宋"
"作者" = "邵雍"
"内容" = "一去二三里，烟村四五家。亭台六七座，八九十枝花。"

[["古诗"]]
"标题" = "江楼感旧"
"朝代" = "唐"
"作者" = "赵嘏"
"内容" = "独上江楼思渺然，月光如水水如天。同来望月人何处？风景依稀似去年。"

[["古诗"]]
"标题" = "金陵酒肆留别"
"朝代" = "唐"
"作者" = "李白"
"内容" = "风吹柳花满店香，吴姬压酒唤客尝。金陵子弟来相送，欲行不行各尽觞。请君试问东流水，别意与之谁短长。"

[["古诗"]]
"标题" = "舟夜书所见"
"朝代" = "清"
"作者" = "查慎行"
"内容" = "月黑见渔灯，孤光一点萤。微微风簇浪，散作满河星。"

