[tool.poetry]
name = "数据迁移"
version = "0.1.0"
description = ""
authors = ["Robert Zhang <asterix314@163.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^2.7.18"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
